export const VEHICLE_DATA: Record<string, string[]> = {
    "Acura": ["ILX", "Integra", "MDX", "NSX", "RDX", "RLX", "TLX", "ZDX"],
    "Alfa Romeo": ["4C", "Giulia", "Stelvio", "Tonale"],
    "Aston Martin": ["DB11", "DBX", "DBS", "Vantage"],
    "Audi": ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "R8", "e-tron GT", "RS3", "RS5", "RS6", "RS7", "RS Q8", "S3", "S4", "S5", "S6", "S7", "S8", "SQ5", "SQ7", "SQ8", "TT"],
    "Bentley": ["Bentayga", "Continental GT", "Flying Spur"],
    "BMW": ["2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "8 Series", "i4", "i7", "iX", "M2", "M3", "M4", "M5", "M8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z4"],
    "Buick": ["Enclave", "Encore", "Encore GX", "Envision"],
    "Cadillac": ["CT4", "CT5", "Escalade", "Escalade ESV", "LYRIQ", "XT4", "XT5", "XT6"],
    "Chevrolet": ["Blazer", "Bolt EV", "Bolt EUV", "Camaro", "Colorado", "Corvette", "Equinox", "Express", "Malibu", "Silverado 1500", "Silverado 2500HD", "Silverado 3500HD", "Suburban", "Tahoe", "Trailblazer", "Traverse", "Trax"],
    "Chrysler": ["300", "Pacifica", "Voyager"],
    "Dodge": ["Challenger", "Charger", "Durango", "Hornet"],
    "Ferrari": ["296 GTB", "296 GTS", "812 GTS", "F8 Spider", "F8 Tributo", "Portofino M", "Roma", "SF90 Spider", "SF90 Stradale"],
    "Fiat": ["500X"],
    "Ford": ["Bronco", "Bronco Sport", "Edge", "Escape", "Expedition", "Explorer", "F-150", "F-150 Lightning", "F-250 Super Duty", "F-350 Super Duty", "Maverick", "Mustang", "Mustang Mach-E", "Ranger", "Transit", "Transit Connect"],
    "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
    "GMC": ["Acadia", "Canyon", "Hummer EV Pickup", "Hummer EV SUV", "Savana", "Sierra 1500", "Sierra 2500HD", "Sierra 3500HD", "Terrain", "Yukon", "Yukon XL"],
    "Honda": ["Accord", "Civic", "CR-V", "HR-V", "Odyssey", "Passport", "Pilot", "Ridgeline"],
    "Hyundai": ["Elantra", "Ioniq 5", "Ioniq 6", "Kona", "Nexo", "Palisade", "Santa Cruz", "Santa Fe", "Sonata", "Tucson", "Venue"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
    "Jaguar": ["E-PACE", "F-PACE", "F-TYPE", "I-PACE", "XF"],
    "Jeep": ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Grand Cherokee L", "Grand Wagoneer", "Renegade", "Wagoneer", "Wrangler"],
    "Kia": ["Carnival", "EV6", "Forte", "K5", "Niro", "Rio", "Seltos", "Sorento", "Soul", "Sportage", "Stinger", "Telluride"],
    "Lamborghini": ["Aventador", "Huracan", "Urus"],
    "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Lexus": ["ES", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "RZ", "UX"],
    "Lincoln": ["Aviator", "Corsair", "Nautilus", "Navigator"],
    "Lucid": ["Air"],
    "Maserati": ["Ghibli", "Grecale", "Levante", "MC20", "Quattroporte"],
    "Mazda": ["CX-30", "CX-5", "CX-50", "CX-9", "CX-90", "Mazda3", "MX-5 Miata"],
    "McLaren": ["720S", "765LT", "Artura", "GT"],
    "Mercedes-Benz": ["A-Class", "C-Class", "CLA", "CLS", "E-Class", "EQB", "EQE", "EQS", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "S-Class", "SL", "Sprinter"],
    "MINI": ["Clubman", "Convertible", "Countryman", "Hardtop 2 Door", "Hardtop 4 Door"],
    "Mitsubishi": ["Eclipse Cross", "Mirage", "Mirage G4", "Outlander", "Outlander PHEV", "Outlander Sport"],
    "Nissan": ["Altima", "Ariya", "Armada", "Frontier", "GT-R", "Kicks", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Sentra", "Titan", "Titan XD", "Versa", "Z"],
    "Polestar": ["Polestar 2", "Polestar 3"],
    "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
    "Ram": ["1500", "1500 Classic", "2500", "3500", "ProMaster", "ProMaster City"],
    "Rivian": ["R1S", "R1T"],
    "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Spectre"],
    "Subaru": ["Ascent", "BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "WRX"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
    "Toyota": ["4Runner", "bZ4X", "Camry", "Corolla", "Corolla Cross", "Crown", "GR86", "GR Corolla", "GR Supra", "Highlander", "Prius", "Prius Prime", "RAV4", "RAV4 Prime", "Sequoia", "Sienna", "Tacoma", "Tundra", "Venza"],
    "Volkswagen": ["Arteon", "Atlas", "Atlas Cross Sport", "Golf GTI", "Golf R", "ID.4", "Jetta", "Taos", "Tiguan"],
    "Volvo": ["C40 Recharge", "S60", "S90", "V60 Cross Country", "V90 Cross Country", "XC40", "XC40 Recharge", "XC60", "XC60 Recharge", "XC90", "XC90 Recharge"],
    "Other": ["Other"]
};
